[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pynado"
version = "0.1.4"
description = "A friendly, Pythonic wrapper for the Nado Protocol SDK"
readme = "README.md"
license = "MIT"
authors = [
  { name = "apine", email = "a@b.com" },
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
requires-python = ">=3.9"
dependencies = [
    "nado-protocol",
    "pandas",
    "python-dotenv",
    "setuptools",
]

[project.urls]
"Homepage" = "https://github.com/apine/pynado"
"Bug Tracker" = "https://github.com/apine/pynado/issues"
